name: Source Workflow

on:
  workflow_dispatch:
  release:
    types: [prereleased]

run-name: ${{ github.actor }} is testing out GitHub Actions  🚀

jobs:
  trigger:
    runs-on: ubuntu-latest
    env:
      NEST_VERSION: ${{ github.ref_name}}
    steps:
      - name: get the prerelease tag
        run: echo "GITHUB_REFNAME = ${GITHUB_REF_NAME}"
      - name: trigger the automated test in another repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: '${{ secrets.API_TOKEN_GITHUB }}'
          repository: nest/nest-simulator-examples
          event-type: test-trigger
          client-payload: '{"tag": "${{ github.ref_name }}"}'

