---
name: "Test workflow dispatch"
# set this to push on specific branch or tag like release candidate
on:
  workflow_dispatch:
    inputs:
      nest_version:
        description: 'NEST version'
        required: true
        type: choice
        options:
          - $GITHUB_REF_NAME
          - nest_3.8
          - nest_3.9
          - master


jobs:
  test-dropdown:
    runs-on: ubuntu-latest

    env:
      NAME: ${{inputs.nest_version }}
      DISPLAY_NAME: "EBRAINS-24.04"
    steps:
      name: display
      run: echo "$NAME"
