name: Source Workflow

on:
  workflow_dispatch:
  release:
    types: [prereleased]

run-name: ${{ github.actor }} is testing out GitHub Actions  🚀

jobs:
  trigger:
    runs-on: ubuntu-latest
    env:
      NEST_VERSION: ${GITHUB_REF_NAME}
    steps:
      - name: get the prerelease tag
        run: echo "GITHUB_REFNAME = ${GITHUB_REF_NAME}"
      - name: "Checkout new branch in examples repo"
        uses: GuillaumeFalourd/create-other-repo-branch-action@v1.5
        with:
          repository_owner: nest
          repository_name: nest-simulator-examples
          new_branch_name: $NEST_VERSION
          access_token: ${{ secrets.API_TOKEN_GITHUB}}

